name: build
on:
  push:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        docker compose up -d
        go test -mod=vendor -covermode=count ./app/... -coverprofile $GITHUB_WORKSPACE/cover.out
        ls -la

    - name: Submit coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: $GITHUB_WORKSPACE/cover.out
      # run: |
      #   go get golang.org/x/tools/cmd/cover
      #   go get github.com/mattn/goveralls
      #   ls -la $(go env GOPATH)/bin
        # $(go env GOPATH)/bin/goveralls -coverprofile=$GITHUB_WORKSPACE/cover.out -service=github -repotoken ${{ secrets.COVERALLS_TOKEN }}
