name: build
on:
  push:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      run: |
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls

    - name: Test
      run: |
        docker compose up -d
        go test -mod=vendor -covermode=count ./app/... -coverprofile $GITHUB_WORKSPACE/cover.out

    - name: Submit coverage
      run: $(go env GOPATH)/bin/goveralls -coverprofile=$GITHUB_WORKSPACE/cover.out -service=github -repotoken ${{ secrets.COVERALLS_TOKEN }}
