name: build
on:
  push:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        docker compose up -d
        go test -mod=vendor -covermode=count ./app/... -coverprofile $GITHUB_WORKSPACE/cover.out

    - name: Submit coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out
