name: build
on:
  push:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Test
      run: |
        docker compose up -d
        go test -mod=vendor ./app/... -coverprofile $GITHUB_WORKSPACE/cover.out
